name: 'Docker build and release'
on:
  push:
    branches:
      - 'master'
    tags:
      - 'production-*'

env:
  IMAGE: cr.brightbox.com/${{ secrets.CR_ACCOUNT }}/postfix/postfix

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.IMAGE }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=ref,event=tag
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: buildx
      - name: Login to Container Registry
        uses: docker/login-action@v2
        with:
          registry: cr.brightbox.com
          username: ${{ secrets.CR_USERNAME }}
          password: ${{ secrets.CR_SECRET }}
      - name: Docker build
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
